### ISSUE TITLE
How to support additional languages?

### ISSUE THREAD

**Issue by DamnedScholar** [alibaba/structure-view#12]
I thought I might take a crack at implementing Python, but I'm struggling to figure out how to get the package to recognize a new language. I made [a `python.js` file](https://github.com/DamnedScholar/atom-structure-view/blob/python/lib/tag-generators/python.js) with the obligatory `parseFile()`, that includes a Python-parsing library (`sarama.js`) and is supposed to spit out dummy content to the tree while giving me a log of the `ast` object so that I can take a look at it and see how it's built. However, when I toggle `structure-view` in my test Python file, it appears to load forever. What am I missing?

**Comment by Joouis** [comment]
@DamnedScholar Sorry for replying late and it's really happy to see your try. I will give a code review for your work recently.

**Comment by LeGoffLoic** [comment]
Hey @DamnedScholar 
If your python.js doesn't work, would it be worth trying to implement ctags ? That could produce a better result thant what it actually does.

**Comment by DamnedScholar** [comment]
I was exploring this in order to move away from ctags-related packages, since it's cumbersome and confusing to use and doesn't actually provide much value to a novice user. My amateur impression is that ctags was a great code tool in the '90s; I felt like my time could be better spent in implementing a modern analysis library than in figuring out if I could bring ctags up to what I needed. After not receiving a response, I dropped this project. [Very shortly thereafter](http://blog.atom.io/2017/09/12/announcing-atom-ide.html), the `atom-ide` project was announced. I now use [`ide-python`](https://atom.io/packages/ide-python) with the outline view built into [`atom-ide-ui`](https://atom.io/packages/atom-ide-ui) and it works great.

**Comment by LeGoffLoic** [comment]
Atom-ide-ui outline doesn't work for me, it loads indefinitely
