### ISSUE TITLE
Arrows the only trigger for TagTree toggling?

### ISSUE THREAD

**Issue by gitarian** [alibaba/structure-view#13]
Hi,

what do you think about making the arrows (maybe the symbol letters as well) the only trigger for node collapse/expansion?
Currently every "click for jump" collapses the respective node which is a bit cumbersome, especially when there are deeper structures along this very descendent path.

**Comment by Joouis** [comment]
@gitarian Sorry for replying late. What do you think about double click to trigger nodes collapse/expansion?
I do realize it is inappropriate that one action results in two changes, so I have changed single click to double for trigger in my work.

**Comment by gitarian** [comment]
Hi,
I have problems with my mail notifications, thus I'm late as well.

Double click would be ok. Initially, the tree should be fully expanded. Then I could use single click for structure navigation which is the major purpose of this package.

I‘m also behind my schedule (needed quite some time to read up and understand the import and export mechanisms in JavaScript in general and Atom/Node.js in particular). I hope to to make good progress my simple parser within the upcoming weeks.

**Comment by Joouis** [comment]
v0.2.0 has been released, it should meet your expectation, just upgrade and try it  😄
