### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kazerniel** [alibaba/structure-view#25]
I get the following error when trying to install the package:

```
Failed to install structure-view because Git was not found.

The structure-view package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.
```
After I got the error the first time, I did install GitHub Desktop for Windows and added its path as an environmental variable, but I'm still getting the error.

**apm -v** outputs the following:
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python
git
visual studio
```

**Comment by johngrant4est** [comment]
Are you on Windows ? I think I had the same problem, the resolution is in the comments here:
https://github.com/orktes/atom-react/issues/106

**Comment by kazerniel** [comment]
Thanks, it worked! (I'm on Win7.)
