### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by john-cj** [alibaba/structure-view#35]
Atom 1.34.0, Win 7

When I try to install this package, it animates "Install" button for some time, then animation stops and that's all. The package is not installed. Tried several times, with Atom restarting as well.

**Comment by johngrant4est** [comment]
Hi, installing on Windows requires that you download and install Git. I got the latest here :
[https://git-scm.com/download/win](url)
Please note this is different from the Github desktop.
I installed using command :
`apm install structure-view`
Try that.

**Comment by john-cj** [comment]
Thanks. So, I close this issue as resolved.
