### ISSUE TITLE
Git required to install?

### ISSUE THREAD

**Issue by onetrev** [alibaba/structure-view#4]
I noticed this package failed to install for me because it requires git. Since git is now included in Atom, I wonder if this can be avoided? Totally just a long shot, but it would be nice to not have to install git when I don't need to as I use Atom and GitKraken for my git clients. Thanks!!

**Comment by Joouis** [comment]
@onetrev Sorry that git is required for the moment, one of dependencies [jsctags](https://github.com/ramitos/jsctags) needs it.
[Esprima](https://github.com/jquery/esprima) is the first choice to parse AST tree of javascript file, but in the situations below would meet trouble:
- JS script with lexical error.
- Variant of Javascript like JSX.
- Few cases that JS script works well but esrima emits error.
jsctags is also a popular parser which is more robust, it can handle lexical error and generate AST tree as well as it can parse JSX file.
Robustness is really important, so structure-view takes jsctags as substitution.
