### ISSUE TITLE
Install blocked in setting panel

### ISSUE THREAD

**Issue by yubaoquan** [alibaba/structure-view#7]
I tried to install this package a whole day, but it blocked for very long time. I tried to install other atom packages, but never seen this blocking phenomenon.
<img width="798" alt="screen shot 2017-09-24 at 12 05 16 pm" src="https://user-images.githubusercontent.com/2340296/30779350-bd5df5ca-a0b3-11e7-82ea-5233554f81c8.png">

**Comment by Joouis** [comment]
@yubaoquan Um... Maybe there are some problems with your network or proxy. You can also try this way:

1. Download the latest version of package from [here](https://github.com/alibaba/structure-view/releases)
2. Unzip or decompress it
3. Go to that folder and run: `apm link` that will create a symbolic link from that package to your `~/.atom/packages` folder
4. Reload the Atom
