### ISSUE TITLE
Install of 0.1.4 requires Git?

### ISSUE THREAD

**Issue by gitarian** [alibaba/structure-view#8]
Why do I need to have Git installed in order to install Structure-View?

```
Installing “structure-view@0.1.4” failed.Hide output…
Failed to install structure-view because Git was not found.

The structure-view package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.
```

Gitarian

**Comment by gitarian** [comment]
Update: Manual installation of release 0.1.4 seems to have worked. But trying to run it (Structure View: Show) throws another error:

```
Failed to activate the structure-view package
Cannot find module 'jquery'
Show Stack Trace
The error was thrown from the structure-view package. You can help by creating an issue. Please explain what actions triggered this error.
```

Strange, seems I'm the only one having these problems.

**Comment by Joouis** [comment]
#4 Duplicated issue

**Comment by gitarian** [comment]
Hi John,

thank you for explaining the root causes - and sorry for duplication, I should have read better in the first place.

After installing Git it does work. Now I cant turn my actual goal, adding support for another (simple) language. 
But since I'm totally new to Atom and Git these will become some trial & error fun. ;-)

**Comment by Joouis** [comment]
Wow PR is welcomed!!! 💪

**Comment by gitarian** [comment]
Hi John,

I just finished my first small change (support for soft-wrapped lines).

Though I'm a total newbie regarding GitHub, I did get the general procedure goes like this.

1. Clone and prepare the repository --> [done]
2. Make your changes --> [done]
3. Commit (to local repo) --> [done]

**What's next?** Push is blocked (of course). Do I have to fork you repo to propagate my changes to you?

**Comment by Joouis** [comment]
You should fork this project first, then commit and push to your repo, at last submit a pull request.
